name: 'Publish PHPDoc'
description: 'Generate docs with phpDocumentor & publish to GitHub Pages'

inputs:
  phpdoc-build-path:
    description: 'phpDocumentor output path'
    required: false
    default: '.phpdoc/build'
  phpdoc-cache-path:
    description: 'phpDocumentor cache path'
    required: false
    default: '.phpdoc/cache'

outputs:
  page-url:
    description: 'URL to deployed GitHub Pages'
    value: ${{ steps.deploy-pages.outputs.page_url }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure GitHub Pages
      uses: actions/configure-pages@v5

    - name: Cache phpDocumentor
      id: phpdocumentor-cache
      uses: actions/cache@v4
      with:
        path: "${{ inputs.phpdoc-cache-path }}"
        key: "${{ runner.os }}-phpdocumentor-${{ github.sha }}"
        restore-keys: |
          ${{ runner.os }}-phpdocumentor-

    - name: Generate docs with phpDocumentor
      shell: bash
      #language=bash
      run: docker compose run --rm phpdoc -t ${{ inputs.phpdoc-build-path }}

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ inputs.phpdoc-build-path }}

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      id:   deploy-pages
