name: 'Run Pest'
description: 'Run PHP Pest tests'

inputs:
  php-version:
    description: 'PHP Version'
    required: false
    default: '8.1'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        tools: composer:v2
        coverage: xdebug

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: |
          vendor
        key: ${{ runner.os }}-php-${{ inputs.php-version }}-${{ hashFiles('composer.json') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ inputs.php-version }}-
          ${{ runner.os }}-php-

    - name: Install dependencies
      #language=bash
      run: composer install --no-interaction --no-progress --prefer-dist --optimize-autoloader

    - name: Run Pest
      #language=bash
      run: ./vendor/bin/pest --ci
